
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: demo_festalab_development

test:
  <<: *default
  database: demo_festalab_test

production:
  <<: *default
  database: demo_festalab_production
